resources:
- ./../../../../../../apps/hello-nginx/v1
- ./hello-nginx/1.0
- namespace.yaml

namespace: hello-nginx-app

configMapGenerator:
- name: index-html-configmap
  behavior: replace
  files:
  - index.html
